### ISSUE TITLE
Surf and Paddle

### ISSUE THREAD

**Issue by samkap** [crowjm/tiy_assignments#4]
The date on the blog post on Surf and Paddle doesn't hover like the rest of the links

Also, when I go to the regular zoom (Cmd + 0), Darth jumps down to the next line and messes with the alignment of maps and the address. In addition the nav is outside of the header, visually:
![crowjm github io tiy_assignments 06_cool_design_agency](https://cloud.githubusercontent.com/assets/2152574/6107718/cdc70f6a-b032-11e4-9cd2-8a3d239f9f8f.png)

**Comment by jesse-stew** [comment]
Changed the date on Surf and Paddle from being in a span underlined to being an active link, so it hovers now. 
Thanks for the help fixing the Cool Design Agency problem. :)
