### ISSUE TITLE
Restaurant Style Tiles Feedback 

### ISSUE THREAD

**Issue by samkap** [crowjm/tiy_assignments#7]
(you already read this but for archival purposes, and with the details I deleted earlier)
## Overall

1) and 2) the type is awesome and the color schemes are appropriate for the two directions but the colors of one seem more on FLEEK and more in tune with them. I'd be interested in seeing two with colors like one.
## v1

Everyone was really drawn to this yesterday in class. I believe for the yellow text will work fine on the background _if_ the headline 1/2/3 type is a few pxs/fractions of ems larger. 
## v2

The dark blue, now that I've looked at it somewhere, does feel slightly too muted for who bouldin is. I think the type hierarchy and colors is successful with the dark color background , so if colors from one come in, I think a darker background color might work well.
## v3

The concept behind the neon signs really comes through clearly here for the association locals have with South 1st. I believe the colors could be a bit more bright, and saturated so they look less pastel against the background and read more as neon, so this can have the same pow impact of one.

**Comment by jesse-stew** [comment]
Thank you! I'm excited to get feedback on the color changes; I think they're much more on point!
